"""initial migration

Revision ID: 4fcba5fe4b06
Revises: 
Create Date: 2025-10-22 17:38:16.874160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fcba5fe4b06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('pattern_number', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patterns'))
    )
    op.create_table('pattern_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], name=op.f('fk_pattern_requirements_pattern_id_patterns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pattern_requirements'))
    )
    with op.batch_alter_table('pattern_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pattern_requirements_pattern_id'), ['pattern_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], name=op.f('fk_projects_pattern_id_patterns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_pattern_id'), ['pattern_id'], unique=False)

    op.create_table('project_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('material_type', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_project_materials_material_id_materials')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_materials_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_materials'))
    )
    with op.batch_alter_table('project_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_materials_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_materials_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_materials_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_materials_material_id'))

    op.drop_table('project_materials')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_pattern_id'))

    op.drop_table('projects')
    with op.batch_alter_table('pattern_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pattern_requirements_pattern_id'))

    op.drop_table('pattern_requirements')
    op.drop_table('patterns')
    op.drop_table('materials')
    # ### end Alembic commands ###
