"""remove materials, add project images, measurment_notes, and  deadline

Revision ID: b9c5b485b893
Revises: 8a5ff6594b04
Create Date: 2026-05-26 22:02:31.864825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c5b485b893'
down_revision = '8a5ff6594b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(), nullable=True),
    sa.Column('secure_url', sa.String(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_images_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_images'))
    )
    with op.batch_alter_table('project_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_images_project_id'), ['project_id'], unique=False)

    
    with op.batch_alter_table('project_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_materials_material_id'))
        batch_op.drop_index(batch_op.f('ix_project_materials_project_id'))

    op.drop_table('project_materials')
    op.drop_table('materials')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('measurement_notes', sa.String(), nullable=True))
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('measurement_notes')
        batch_op.drop_column('deadline')

    op.create_table('project_materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('material_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_project_materials_material_id_materials')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_materials_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_materials'))
    )
    with op.batch_alter_table('project_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_materials_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_materials_material_id'), ['material_id'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('material_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('supplier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_materials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    with op.batch_alter_table('project_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_images_project_id'))

    op.drop_table('project_images')
    # ### end Alembic commands ###
